# [Scikit-learnでデータをスケール変換する](https://helve-blog.com/posts/python/scikit-learn-feature-scaling/)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

## StandardScalerの使用例

以下の2次元配列`x`を用意する。

In [2]:
x = np.arange(0, 8, 1.).reshape(-1, 2)
print(x)
print(x.mean(axis=0))
print(x.std(axis=0))

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]]
[3. 4.]
[2.23606798 2.23606798]


In [3]:
sscaler = preprocessing.StandardScaler() # インスタンスの作成

sscaler.fit(x)           # xの平均と標準偏差を計算
y = sscaler.transform(x) # xを変換

print(y)
print(y.mean(axis=0))
print(y.std(axis=0))

[[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]
[0. 0.]
[1. 1.]


以下の通り、変換後の配列`y`は各列とも平均は0, 標準偏差は1となった。

ここで、以下は上と同じ操作となる。

In [6]:
y = sscaler.fit_transform(x) # xを変換した結果が返る

print(y)
print(y.mean(axis=0))
print(y.std(axis=0))

[[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]
[0. 0.]
[1. 1.]


# EOF